name: CT Default Files

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: "Version"

      run: echo "version=$(date +%Y.%m)" >> $GITHUB_ENV

    - uses: actions/checkout@v2


    - name: MagicMirror-Docker Utils
      run: |
        cp ./MagicMirrorServer/config/config.js ./js/config.js 
        cp ./MagicMirrorServer/modules/default/* ./modules/default 
        zip -r -X MagicMirror-Docker-utils.zip js/* modules/*
        ls -lah
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: v${{ env.version }}
        prerelease: false
        files: |
          MagicMirror-Docker-utils.zip

