name: SYNC README

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

    paths:
      - README.md    


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
   
   
    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: francescozanti/magicmirror-docker